# Neural Network to Determine Test Results of Patients

## What Are We Solving?

We are creating this neural network to predict the test results of patients in the data set. There are three options, normal, abnormal, and inconclusive making it a multi-class classification problem. This would mean use if multinominal logistic regression to create our model, but for the time frame of this project, we are going to merge the normal and inconclusive cases to have a binary classification problem.

#### Note:
Any words in bold within this file visit the file `glossary.md` in the github repository.

### Import Libraries and Dataset

In [2]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from scipy import stats
import matplotlib.pyplot as plt
import urllib.request
import io
import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from opacus import PrivacyEngine
from opacus.utils.batch_memory_manager import BatchMemoryManager

df = pd.read_csv("../data/healthcare_dataset.csv")
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,Normal
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,Inconclusive
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,Normal
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,Abnormal
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,Abnormal

## Pre-processing the Data

### Binary Classification

To begin the phase of preprocessing, we must manipulate our target column to become a binary classification problem. Using the `replace` method, we start by splitting the data in the `Test Results` column from three cases to two, `Abnormal` and `Non-Abnormal`.

In [3]:
df['Test Results'] = df['Test Results'].replace({
    'Normal' : 'Non-Abnormal',
    'Inconclusive' : 'Non-Abnormal',
    'Abnormal' : 'Abnormal'})

df['Test Results'] = (df['Test Results'] == 'Abnormal').astype(int)
df.head()

,Name,Age,Gender,Blood Type,Medical Condition,Date of Admission,Doctor,Hospital,Insurance Provider,Billing Amount,Room Number,Admission Type,Discharge Date,Medication,Test Results
0,Bobby JacksOn,30,Male,B-,Cancer,2024-01-31,Matthew Smith,Sons and Miller,Blue Cross,18856.281306,328,Urgent,2024-02-02,Paracetamol,0
1,LesLie TErRy,62,Male,A+,Obesity,2019-08-20,Samantha Davies,Kim Inc,Medicare,33643.327287,265,Emergency,2019-08-26,Ibuprofen,0
2,DaNnY sMitH,76,Female,A-,Obesity,2022-09-22,Tiffany Mitchell,Cook PLC,Aetna,27955.096079,205,Emergency,2022-10-07,Aspirin,0
3,andrEw waTtS,28,Female,O+,Diabetes,2020-11-18,Kevin Wells,"Hernandez Rogers and Vang,",Medicare,37909.782410,450,Elective,2020-12-18,Ibuprofen,1
4,adrIENNE bEll,43,Female,AB+,Cancer,2022-09-19,Kathleen Hanna,White-White,Aetna,14238.317814,458,Urgent,2022-10-09,Penicillin,1

### Removing Personally Identifiable Information (PII)

When we import our csv file to create our model, we want to get rid of **PII** that will not be relevant to our problem. This allows us to better utilize the data while maintaining a base level of privacy. We will remove the columns `Name`, `Doctor`, `Hospital`, `Room Number`, `Insurance Provider`, and `Billing Amount`. We remove `Billing Amount` because they are large, unique to each person, and do not help us in our classification.

In [4]:
df_clean = df.drop(columns=[
    'Name', 'Doctor', 'Hospital', 'Billing Amount', 'Room Number', 'Insurance Provider', 'Date of Admission', 'Discharge Date', 'Medication'])

### One-hot Encoding

**One-hot encoding** is a preprocessing method that allows machine-learning models to understand our data, and in pandas it is performed using the method `get_dummies`. It converts the categorical variables into numerical values, creating a binary column for each category with a feature and assigning a 1 if it belongs to that category, 0 otherwise.

In [5]:
categorical_cols = ['Gender', 'Blood Type', 'Medical Condition', 
                     'Admission Type']
df_processed = pd.get_dummies(df_clean, columns=categorical_cols)

### Split, Scale, and Standardize

We separate the **features** (X) from the **target** (y) so the model will learn only from the inputs. A **train/test split** is used to evaluate how well the model generalizes to new data. **Standarizing** the features ensures all of the numerical values share a similar scale. This prevents large magnitude features `(e.g. Billing Amount)` from dominating the gradient updates and helps optimization methods like **stochastic gradient descent** (what we are using to train) converge faster with more stability.

In [6]:
# split features (X) and target (y)
X = df_processed.drop('Test Results', axis=1)
y = df_processed['Test Results']

# test cases
print(f"Shape of X: {X.shape}")
print(f"Shape of y: {y.shape}")

# create train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# standardize numerical features using StandardScaler (Age
scaler = StandardScaler()

X_train['Age'] = scaler.fit_transform(X_train[['Age']])
X_test['Age'] = scaler.transform(X_test[['Age']])
# test
print(X_train.info)
# originally converted to numpy arrays before using the scaler, but now I have to do it now
X_train = X_train.values.astype(np.float32)
X_test = X_test.values.astype(np.float32)
y_train = y_train.values.astype(np.float32)
y_test = y_test.values.astype(np.float32)

Shape of X: (55500, 20)
Shape of y: (55500,)
<bound method DataFrame.info of             Age  Gender_Female  Gender_Male  Blood Type_A+  Blood Type_A-  \
45174 -1.508744           True        False          False          False
10214 -1.508744          False         True          False          False
43199  1.500326           True        False           True          False
31626  1.449325           True        False          False          False
9273  -1.304739           True        False          False          False
...         ...            ...          ...            ...            ...
44732 -1.253738           True        False          False          False
54343 -0.998732          False         True          False          False
38158 -1.406741           True        False          False          False
860    1.245320          False         True           True          False
15795 -0.947731           True        False          False          False

       Blood Type_AB+  Blood Type_AB-  Blood Type_B+  Blood Type_B-  \
45174           False           False          False          False
10214           False           False          False           True
43199           False           False          False          False
31626           False           False           True          False
9273             True           False          False          False
...               ...             ...            ...            ...
44732           False           False          False           True
54343           False            True          False          False
38158           False           False          False           True
860             False           False          False          False
15795           False           False           True          False

       Blood Type_O+  Blood Type_O-  Medical Condition_Arthritis  \
45174           True          False                         True
10214          False          False                        False
43199          False          False                         True
31626          False          False                        False
9273           False          False                        False
...              ...            ...                          ...
44732          False          False                        False
54343          False          False                        False
38158          False          False                        False
860            False          False                        False
15795          False          False                        False

       Medical Condition_Asthma  Medical Condition_Cancer  \
45174                     False                     False
10214                     False                     False
43199                     False                     False
31626                      True                     False
9273                      False                     False
...                         ...                       ...
44732                     False                      True
54343                     False                     False
38158                     False                     False
860                        True                     False
15795                     False                     False

       Medical Condition_Diabetes  Medical Condition_Hypertension  \
45174                       False                           False
10214                        True                           False
43199                       False                           False
31626                       False                           False
9273                        False                           False
...                           ...                             ...
44732                       False                           False
54343                       False                            True
38158                       False                           False
860                         False                           False
15795                       False                           False

       Medical Condition_Obesity  Admission Type_Elective  \
45174                      False                     True
10214                      False                    False
43199                      False                    False
31626                      False                     True
9273                        True                     True
...                          ...                      ...
44732                      False                     True
54343                      False                    False
38158                       True                    False
860                        False                    False
15795                       True                    False

       Admission Type_Emergency  Admission Type_Urgent
45174                     False                  False
10214                      True                  False
43199                      True                  False
31626                     False                  False
9273                      False                  False
...                         ...                    ...
44732                     False                  False
54343                      True                  False
38158                      True                  False
860                        True                  False
15795                     False                   True

[44400 rows x 20 columns]>

## Convert To Tensors

PyTorch models operate on **tensors**, which are a specialized data structure similar to arrays and matrices. They are used to encode the inputs and outputs of a model along with the models parameters. We convert our numpy arrays to tensors to allow the model to compute gradients and update weights during training. Wrapping the tensors in the **TensorDataset** and the **DataLoader** helps efficiency in **mini-batch** processing and **shuffling** during training and testing.

In [7]:
# convert the numpy arrays to PyTorch tensors
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1, 1)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1, 1)

# create DataLoaders for batch processing
train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
test_dataset = TensorDataset(X_test_tensor, y_test_tensor)

train_loader = DataLoader(train_dataset, batch_size=64, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=64, shuffle=False)

## Addressing the Class Imbalance

When originally creating all of this, I was unaware of the fact that adjusting the multi-class to binary classification problem would probe the neural network to only choose zero. There was no repercussions for this act and the accuracy would stay at 66%. This problem needs to be addressed and dealt with. Since I am using this data to implement differential privacy, I can't directly look at the data. So I am going to assume a ratio of 2:1 for 0s and 1s and use that to apply weights. I am doing this before the neural network creation only because I realized this after creating it and it is important when reading through the rest of the file.

In [8]:
# set an assumed weight value and create the loss function with this later on
weight = 2.0
pos_weight = torch.tensor([weight], dtype = torch.float32)

## Create the Neural Network

### What is a Neural Network?

This phrase is thrown around a lot in the computer science world. *Neural Network*. Sounds fancy. When I was a freshman in college I heard this coupled with AI more than my own name. In short, a neural network is comprised of layers of nodes. There is an input layer, a certain amount of hidden layers, and an output layer. The concept of the input and output layer is intuitive, as the input is where your processed data enters, and the output layer provides the prediction. The hidden layers are consisted of neurons, and in our training cases we use dropout, which is described below.

### Explaining the Code

We create a class, `MedicalNN`, that takes in the parameter `nn.Module`. This is the yadaydyaydyadya. Our initialization function starts by creating the first layer which is our input to our hidden. `ReLU` (Rectified Linear Unit) is an activation function defined by the non-negative part of its argument. We use dropout while training to minimize co-adpatation. It works by shutting down a random number of neurons from a layer. The number 0.2 used is the dropout rate and it is the number of neurons zeroed out.

In [9]:
class MedicalNN(nn.Module):
    def __init__(self, input_dim):
        super(MedicalNN, self).__init__()
        # first layer is input to hidden
        self.layer1 = nn.Linear(input_dim, 64)
        # second is hidden to hidden
        self.layer2 = nn.Linear(64, 32)
        # third is hidden to output
        self.layer3 = nn.Linear(32, 1)
        self.relu = nn.ReLU()

    def forward(self, x):
        x = self.layer1(x)
        x = self.relu(x)
        
        x = self.layer2(x)
        x = self.relu(x)
        
        x = self.layer3(x)
        return x

## Non-DP Training

To train this model, we are going to use stochastic gradient descent (SGD). It is an algorithm

In [11]:
# initialize model
input_dim = X.shape[1]
model_sgd = MedicalNN(X.shape[1])

# define optimizer and loss
criterion = nn.BCEWithLogitsLoss(pos_weight=pos_weight)

optimizer_sgd = optim.SGD(model_sgd.parameters(), lr=0.1, momentum=0.0)

num_epochs = 100

print("<----- Training for Non-DP SGD ----->")
for epoch in range(num_epochs):
    model_sgd.train()
    running_loss = 0.0
    
    for inputs, labels in train_loader:
        optimizer_sgd.zero_grad()
        outputs = model_sgd(inputs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer_sgd.step()
        
        running_loss += loss.item()

    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}, Loss: {running_loss/len(train_loader):.4f}")

# Print out the accuracy:
model_sgd.eval()
with torch.no_grad():
    outputs = model_sgd(X_test_tensor)
    # manually applying the sigmoid now
    probabilities = torch.sigmoid(outputs)
    predicted = (outputs > 0.5).float()
    accuracy = (predicted == y_test_tensor).sum() / y_test_tensor.size(0)
    print(f"\nStandard SGD Test Accuracy: {accuracy.item() * 100:.2f}%")

<----- Training for Non-DP SGD ----->
Epoch 10, Loss: 0.9249
Epoch 20, Loss: 0.9237
Epoch 30, Loss: 0.9223
Epoch 40, Loss: 0.9207
Epoch 50, Loss: 0.9193
Epoch 60, Loss: 0.9178
Epoch 70, Loss: 0.9165
Epoch 80, Loss: 0.9157
Epoch 90, Loss: 0.9148
Epoch 100, Loss: 0.9136

Standard SGD Test Accuracy: 64.56%

### TODO:
- opacus implementaion
- take notes on different epsilon and delta values trying to determine which produces best privacy and utility

## Training Using Opacus

Opacus is a library utilized with pytorch to add differential privacy to the machine learning algorithms trained. We are going to write a function, called `train_dp_model`, that we will be able to utilize to complete multiple training instances of the neural network. Using different values for delta and epsilon each time.

In [18]:
def train_dp_model(noise_multiplier, max_grad_norm, epochs=50):
    # initialize the neural network and criterion
    model_dp = MedicalNN(X.shape[1])
    optimizer = optim.SGD(model_dp.parameters(), lr=0.1, momentum=0.9)
    criterion = nn.BCELoss()

    # recreate loader and initialize privacy engine
    train_loader_dp = DataLoader(train_dataset, batch_size=64, shuffle=True)
    privacy_engine = PrivacyEngine()

    # make the model private
    # wrap the model, optimizer, and loader to handle the gradient clipping and noise addition
    model, optimizer, train_loader_dp = privacy_engine.make_private(
        module = model_dp,
        optimizer = optimizer,
        data_loader = train_loader_dp,
        noise_multiplier = noise_multiplier,
        max_grad_norm = max_grad_norm,
    )

    # starting the training
    # printing out the noise and clipping at the top for easy readability
    print(f"\n Training with noise multiplier {noise_multiplier} and gradient clipping {max_grad_norm} \n")

    for epoch in range(epochs):
        model.train()
        running_loss = 0.0

        with BatchMemoryManager(
            data_loader = train_loader_dp,
            max_physical_batch_size = 64,
            optimizer = optimizer
        ) as memory_safe_loader:
            for inputs, labels in memory_safe_loader:
                optimizer.zero_grad()
                outputs = model(inputs)
                loss = criterion(outputs, labels)
                loss.backward()
                optimizer.step()
                running_loss += loss.item()

    # get privacy budget
    epsilon = privacy_engine.get_epsilon(delta = 1e-5)
    # get the accuracy
    # we are going to use the original tensors created at the beginning
    model.eval()
    with torch.no_grad():
        outputs = model(X_test_tensor)
        predicted = (outputs > 0.5).float()
        predictions = (predicted == y_test_tensor).float().sum()
        accuracy = predictions / y_test_tensor.size(0)
        accuracy_val = accuracy.item() * 100

    # print epsilon vals
    print(f"Final Epsilon: {epsilon:.2f}")
    print(f"Test Accuracy: {accuracy_val:.2f}%")

    return epsilon, accuracy_val

### What does this code actually mean?

In the code above, we are training our neural network using differential privacy. We use different epsilon values and noise multipliers to determine which value is best to maintain utility while protecting the users data.

In [20]:
noise_params = [0.5, 1.0, 1.5] 
max_grad_norm = 1.0
results = []

print("Starting DP Training Experiments...")

for nm in noise_params:
    # run epochs
    eps, acc = train_dp_model(noise_multiplier=nm, max_grad_norm=max_grad_norm, epochs=50)
    results.append((nm, eps, acc))

# display in a nice looking table
print("\n\n" + "="*55)
print(f"{'Noise Mult':<15} {'Epsilon':<15} {'Accuracy (%)':<15}")
print("="*55)
for nm, eps, acc in results:
    print(f"{nm:<15} {eps:<15.2f} {acc:<15.2f}")
print("="*55)

Starting DP Training Experiments...

 Training with noise multiplier 0.5 and gradient clipping 1.0

/var/folders/lp/x6g4gh1x47sb4m1nrn0p2cwr0000gn/T/ipykernel_47160/3182172840.py:38: UserWarning: Full backward hook is firing when gradients are computed with respect to module outputs since no inputs require gradients. See https://docs.pytorch.org/docs/main/generated/torch.nn.Module.html#torch.nn.Module.register_full_backward_hook for more details.
  loss.backward()

Final Epsilon: 11.24
Test Accuracy: 66.21%

 Training with noise multiplier 1.0 and gradient clipping 1.0

Final Epsilon: 1.39
Test Accuracy: 66.19%

 Training with noise multiplier 1.5 and gradient clipping 1.0

Final Epsilon: 0.75
Test Accuracy: 64.25%


=======================================================
Noise Mult      Epsilon         Accuracy (%)
=======================================================
0.5             11.24           66.21
1.0             1.39            66.19
1.5             0.75            64.25
=======================================================